name: multitask_rl
exp_name: CartPole-v1

tasks:
  CartPole-v1:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: MlpPolicy
    env:
      name: CartPole-v1
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: param_data/CartPole-v1/data.pt
      k: 200
      num_workers: 4
