name: multitask_rl
exp_name: mix

load_episode_vae: False
episode_len: 10

tasks:
  Atari-Alien:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: AlienNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Alien/200/data.pt
      k: 200
      num_workers: 4

  Atari-BattleZone:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: BattleZoneNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-BattleZone/200/data.pt
      k: 200
      num_workers: 4

  Atari-Boxing:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: BoxingNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Boxing/200/data.pt
      k: 200
      num_workers: 4

  Atari-Jamesbond:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: JamesbondNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Jamesbond/200/data.pt
      k: 200
      num_workers: 4

  Atari-Kangaroo:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: KangarooNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Kangaroo/200/data.pt
      k: 200
      num_workers: 4

  Atari-RoadRunner:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: RoadRunnerNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-RoadRunner/200/data.pt
      k: 200
      num_workers: 4

  Atari-Robotank:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: RobotankNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Robotank/200/data.pt
      k: 200
      num_workers: 4

  Atari-Seaquest:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: SeaquestNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Seaquest/200/data.pt
      k: 200
      num_workers: 4


  Atari-Pong:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: PongNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Pong/200/data.pt
      k: 200
      num_workers: 4

  Atari-Breakout:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: BreakoutNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Breakout/200/data.pt
      k: 200
      num_workers: 4

  Atari-Asteroids:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: AsteroidsNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Asteroids/200/data.pt
      k: 200
      num_workers: 4

  Atari-Enduro:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: EnduroNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Enduro/200/data.pt
      k: 200
      num_workers: 4

  Atari-MsPacman:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: MsPacmanNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-MsPacman/200/data.pt
      k: 200
      num_workers: 4

  Atari-Qbert:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: QbertNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Qbert/200/data.pt
      k: 200
      num_workers: 4

  Atari-SpaceInvaders:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: SpaceInvadersNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-SpaceInvaders/200/data.pt
      k: 200
      num_workers: 4

  Atari-Assault:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: AssaultNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Assault/200/data.pt
      k: 200
      num_workers: 4

  Atari-Amidar:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: AmidarNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Amidar/200/data.pt
      k: 200
      num_workers: 4

  Atari-CrazyClimber:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: CrazyClimberNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-CrazyClimber/200/data.pt
      k: 200
      num_workers: 4

  Atari-Freeway:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: FreewayNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-Freeway/200/data.pt
      k: 200
      num_workers: 4

  Atari-BeamRider:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: BeamRiderNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-BeamRider/200/data.pt
      k: 200
      num_workers: 4

  Atari-UpNDown:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: CnnPolicy
    env:
      name: UpNDownNoFrameskip-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: ${project_root}/param_data/Atari_zoo/Atari-UpNDown/200/data.pt
      k: 200
      num_workers: 4
