name: multitask_rl
exp_name: Walker2d-v4

tasks:
  Walker2d-v4:
    train:
      alg:
        _target_: stable_baselines3.PPO
        policy: MlpPolicy
    env:
      name: Walker2d-v4
      n_eval_episodes: 10
      num_envs: 10
      seed: 42

    param:
      data_root: param_data/Walker2d-v4/data.pt
      normalization_path: param_data/Walker2d-v4/vecnormalize.pkl
      k: 200
      num_workers: 4